### PR TITLE
Added CSS variables for attributes

### PR DESCRIPTION
**Pull request by barryvan**
With this change, attributes are duplicated as CSS variables. There is special handling for URLs. This facilitates additional styling options; for example, it makes it possible to add avatars for contact photos using very basic CSS:

```css
.data-link-icon[data-link-photo^="https" i] {
	width: 1.5em;
	height: 1.5em;
	display: inline-block;
	vertical-align: middle;
	background-image: var(--data-link-photo);
	background-size: cover;
	box-shadow: 0 1px 4px #0008;
	border-radius: 100%;
	margin: -0.5em 0.2em -0.5em 0;
}
```

image

### CODE REVIEW

**Comment by HEmile** [comment]
Hey! This is a pretty cool idea, I like it. Some questions.
1. Is there any performance overhead on larger vaults? 
2. Did you test it when multiple links have the same key but different values? (Especially in the same note?) 
3. This is implemented in the live-preview class. Does it also work in eg the file browser?

**Comment by barryvan** [comment]
Thanks @HEmile! :)

1. I've not done any formal testing, but I've been running it on my vault on my personal machine and haven't noticed performance issues. I have ~1000 notes across ~100 folders and sub-folders.
2. Good catch! This caused a bug which prevented the note from loading. 😳 I've patched this so that we simply put this in as a comma-separated list in the CSS, with no special URL handling. CSS doesn't really have the concept of lists or arrays, and I don't think that it's worth the effort to convert the array to (for example) `--data-link-photo-1: ...; --data-link-photo-2: ...`. I think that that's something to potentially look at as a future enhancement if anyone's interested.
3. It does now! 😆 I've updated the PR to support this. Here's a sample screenshot:

image

Applied CSS:

```css
.data-link-icon[data-link-photo^="https" i]:empty {
	width: 1.5em;
	height: 1.5em;
	display: inline-block;
	vertical-align: middle;
	background-image: var(--data-link-photo);
	background-size: cover;
	box-shadow: 0 1px 4px #0008;
	border-radius: 100%;
	margin: -0.5em 0.2em -0.5em 0;
}

.data-link-icon[data-link-photo^="https" i]:not(:empty)::before {
	content: '';
	width: 1.5em;
	height: 1.5em;
	display: inline-block;
	vertical-align: middle;
	background-image: var(--data-link-photo);
	background-size: cover;
	box-shadow: 0 1px 4px #0008;
	border-radius: 100%;
	margin: -0.5em 0.2em -0.5em 0;
}
```

**Comment by HEmile** [comment]
Thanks for the update! I'll have a more thorough look at the PR soon :) (Sorry if there's a bit of a wait, life is very hectic right now).

**Comment by barryvan** [comment]
No worries! Thanks for all your contributions on this plugin. 😃

**Comment by barryvan** [comment]
Hi HEmile! I just wanted to check in on whether there was anything I could do to help with this PR. 😃  I don't want to push or rush you, though.

**Comment by HEmile** [comment]
Sorry Barry for getting back to you so late. I'll run this version on my vault for a bit to ensure nothing weird breaks. This is a pretty big change! 
If possible, it would be nice to discuss an example of these variables in the README.

**Comment by barryvan** [comment]
Awesome, thanks Emile! I've updated this PR with a bit of an elaboration in the README. When I get time, I'm hoping to write up a blog post that explores my personal usage of this change in a bit more detail, and with somewhat more involved CSS -- although it may just end up being a post on the Obsidian forum!

**Comment by barryvan** [comment]
Hi team! Is there anything I can do to help with this one? I've been running it on my personal vault for several months now with no adverse effects. 😃

**Comment by talkingwires** [comment]
I’ve been looking high and low for a way to accomplish this. It would be great to see this merged with the main project, @HEmile!

**Comment by HEmile** [comment]
Apologies for the wait. It looks good, and is a very useful and intuitive extension :)

**Comment by barryvan** [comment]
Thanks so much @HEmile! 😃

**Pull request merged**
