### PR TITLE
Ensure styles are loaded when the plugin is loaded; style links with spaces in them.

### PR DESCRIPTION
**Pull request by dsummersl**
Fixes two issues:
- When the plugin is loaded, the CSS is not always built (most times for me - and the supercharge links styles are not visible in the Style Settings plugin), and links are not styled. Explicitly generates CSS when the settings tab is constructed.
- LInks with spaces in their name "first last.md" are not captured by the live view plugin - it seems that "first%20last" is not found. Adds explicit decodeURI so that these kinds of files are found.

### CODE REVIEW

**Comment by dsummersl** [comment]
Looking through the list of tickets I think this might fix...
- https://github.com/mdelobelle/obsidian_supercharged_links/issues/156
- https://github.com/mdelobelle/obsidian_supercharged_links/issues/144

**Comment by ngirard** [comment]
> When the plugin is loaded, the CSS is not always built (most times for me - and the supercharge links styles are not visible in the Style Settings plugin), and links are not styled.

I'm also affected by this.

**Comment by Heziode** [comment]
> When the plugin is loaded, the CSS is not always built (most times for me - and the supercharge links styles are not visible in the Style Settings plugin), and links are not styled. Explicitly generates CSS when the settings tab is constructed.

Same issue, waiting for the merge and the release of this fix.

@mdelobelle Do you have time to review?

**Comment by HEmile** [comment]
I hope to have some time this Christmas holidays to update the plugin.

**Comment by nightillusions** [comment]
> When the plugin is loaded, the CSS is not always built (most times for me - and the supercharge links styles are not visible in the Style Settings plugin), and links are not styled. Explicitly generates CSS when the settings tab is constructed.

Yeah! Was searching for a solution, cause this happens to me, too. Nice that this will be fixed in the next release :)

**Comment by sfdrada** [comment]
Is this something we can download/implement manually or do we just wait until the bug patch?
Thanks

**Comment by dsummersl** [comment]
You can go to https://github.com/dsummersl/obsidian_supercharged_links, click the green 'Code' button, download the zip, and unpack it in the `.obsidian/plugins` directory of whatever Obsidian Vault you want to use it in.

**Comment by nightillusions** [comment]
@mdelobelle would be nice if this could be included in a new version soon.

**Comment by HEmile** [comment]
Sorry for the delay, and thank you for your contribution. I'll upload a release with this change include!

**Pull request merged**
